"""Fixed runtime extracted from compiler source 29fe186.

Prototype relocation only. Generated by control compiling `1 2 + drop`.
The seed root and entry point are excluded. No source file is read at runtime.
"""

RUNTIME = r'''
.section .bss
return_stack: .skip 1048576
env_stack: .skip 1048576
env_sp: .skip 8
current_env: .skip 8
.align 16
heap_chunks: .skip 8
heap_ptr: .skip 8
heap_end: .skip 8
free_list: .skip 8
small_free_lists: .skip 512
__argc: .skip 8
__argv: .skip 8
__envp: .skip 8
print_buf: .skip 32

.section .data
bool_true: .ascii "true"
bool_false: .ascii "false"
float_decimal_ten: .long 10
arithmetic_error_msg: .ascii "error: integer arithmetic failed\n"
.equ arithmetic_error_msg_len, . - arithmetic_error_msg
return_stack_overflow_msg: .ascii "error: return stack overflow\n"
.equ return_stack_overflow_msg_len, . - return_stack_overflow_msg
env_stack_overflow_msg: .ascii "error: env stack overflow\n"
.equ env_stack_overflow_msg_len, . - env_stack_overflow_msg
allocation_failure_msg: .ascii "fatal: allocation failed\n"
.equ allocation_failure_msg_len, . - allocation_failure_msg

.section .text
heap_alloc:
    testq %rdi, %rdi
    jz .Lheap_alloc_null
    movq %rdi, %rax
    addq $7, %rax
    jc .Lheap_alloc_oom
    andq $-8, %rax
    cmpq $512, %rax
    ja .Lheap_alloc_large
    leaq small_free_lists(%rip), %r9
    leaq -8(%r9,%rax), %r9
    movq (%r9), %rcx
    testq %rcx, %rcx
    jz .Lheap_alloc_bump
    movq 8(%rcx), %r8
    movq %r8, (%r9)
    leaq 8(%rcx), %rax
    pushq %rax
    jmp .Lheap_alloc_return
.Lheap_alloc_large:
    movq free_list(%rip), %rcx
    xorq %rdx, %rdx
.Lheap_alloc_search:
    testq %rcx, %rcx
    jz .Lheap_alloc_bump
    cmpq %rax, (%rcx)
    jae .Lheap_alloc_reuse
    movq %rcx, %rdx
    movq 8(%rcx), %rcx
    jmp .Lheap_alloc_search
.Lheap_alloc_reuse:
    movq 8(%rcx), %r8
    testq %rdx, %rdx
    jz .Lheap_alloc_reuse_head
    movq %r8, 8(%rdx)
    jmp .Lheap_alloc_return_block
.Lheap_alloc_reuse_head:
    movq %r8, free_list(%rip)
.Lheap_alloc_return_block:
    leaq 8(%rcx), %rax
    pushq %rax
    jmp .Lheap_alloc_return
.Lheap_alloc_bump:
    movq heap_ptr(%rip), %rcx
    testq %rcx, %rcx
    jz .Lheap_alloc_map
    addq $7, %rcx
    andq $-8, %rcx
    movq %rax, %r8
    addq $8, %r8
    jc .Lheap_alloc_oom
    addq %rcx, %r8
    jc .Lheap_alloc_oom
    cmpq heap_end(%rip), %r8
    jbe .Lheap_alloc_commit
.Lheap_alloc_map:
    pushq %rsi
    pushq %r10
    pushq %r11
    pushq %rax
    movq %rax, %rsi
    addq $24, %rsi
    jc .Lheap_alloc_oom
    cmpq $67108864, %rsi
    jae .Lheap_alloc_map_size_ready
    movq $67108864, %rsi
.Lheap_alloc_map_size_ready:
    xorq %rdi, %rdi
    movq $3, %rdx
    movq $34, %r10
    movq $-1, %r8
    xorq %r9, %r9
    movq $9, %rax
    syscall
    popq %rdx
    testq %rax, %rax
    jz .Lheap_alloc_oom
    cmpq $-4095, %rax
    jae .Lheap_alloc_oom
    movq heap_chunks(%rip), %r8
    movq %r8, (%rax)
    movq %rax, %rcx
    addq %rsi, %rcx
    jc .Lheap_alloc_oom
    movq %rcx, 8(%rax)
    movq %rax, heap_chunks(%rip)
    movq %rcx, heap_end(%rip)
    leaq 16(%rax), %rcx
    movq %rdx, %rax
    popq %r11
    popq %r10
    popq %rsi
    movq %rax, %r8
    addq $8, %r8
    addq %rcx, %r8
.Lheap_alloc_commit:
    movq %rax, (%rcx)
    movq %r8, heap_ptr(%rip)
    leaq 8(%rcx), %rax
    pushq %rax
    jmp .Lheap_alloc_return
.Lheap_alloc_null:
    pushq $0
.Lheap_alloc_return:
    subq $8, %r14
    jmpq *(%r14)
.Lheap_alloc_oom:
    movq $2, %rdi
    leaq allocation_failure_msg(%rip), %rsi
    movq $allocation_failure_msg_len, %rdx
    leaq return_stack+1048568(%rip), %rcx
    cmpq %rcx, %r14
    ja return_stack_overflow
    addq $8, %r14
    leaq .Lallocation_failure_write_done_1(%rip), %rax
    movq %rax, -8(%r14)
    jmp write_all
.Lallocation_failure_write_done_1:
    movq $60, %rax
    movq $1, %rdi
    syscall

heap_free:
    testq %rdi, %rdi
    jz .Lheap_free_return
    leaq -8(%rdi), %rax
    movq (%rax), %rdx
    cmpq $512, %rdx
    ja .Lheap_free_large
    leaq small_free_lists(%rip), %rcx
    leaq -8(%rcx,%rdx), %rcx
    movq (%rcx), %rdx
    movq %rdx, 8(%rax)
    movq %rax, (%rcx)
    jmp .Lheap_free_return
.Lheap_free_large:
    movq free_list(%rip), %rcx
    movq %rcx, 8(%rax)
    movq %rax, free_list(%rip)
.Lheap_free_return:
    subq $8, %r14
    jmpq *(%r14)

write_all:
.Lwrite_all_next:
    testq %rdx, %rdx
    jz .Lwrite_all_return
    movq $1, %rax
    syscall
    cmpq $-4, %rax
    je .Lwrite_all_next
    testq %rax, %rax
    jle .Lwrite_all_fail
    addq %rax, %rsi
    subq %rax, %rdx
    jmp .Lwrite_all_next
.Lwrite_all_return:
    subq $8, %r14
    jmpq *(%r14)
.Lwrite_all_fail:
    movq $60, %rax
    movq $1, %rdi
    syscall

print_int:
    movq %rdi, %rax
    leaq print_buf+32(%rip), %rsi
    testq %rax, %rax
    jnz .Lpi_nonzero
    decq %rsi
    movb $48, (%rsi)
    jmp .Lpi_write
.Lpi_nonzero:
    movq %rax, %r15
    jns .Lpi_abs
    negq %rax
.Lpi_abs:
    movq $10, %rcx
.Lpi_digit_loop:
    decq %rsi
    xorq %rdx, %rdx
    divq %rcx
    addb $48, %dl
    movb %dl, (%rsi)
    testq %rax, %rax
    jnz .Lpi_digit_loop
    testq %r15, %r15
    jns .Lpi_write
    decq %rsi
    movb $45, (%rsi)
.Lpi_write:
    leaq print_buf+32(%rip), %rdx
    subq %rsi, %rdx
    movq $1, %rdi
    leaq return_stack+1048568(%rip), %rcx
    cmpq %rcx, %r14
    ja return_stack_overflow
    addq $8, %r14
    leaq .Lprint_int_write_done_2(%rip), %rax
    movq %rax, -8(%r14)
    jmp write_all
.Lprint_int_write_done_2:
    subq $8, %r14
    jmpq *(%r14)

print_uint:
    movq %rdi, %rax
    leaq print_buf+32(%rip), %rsi
    testq %rax, %rax
    jnz .Lpui_digit_loop
    decq %rsi
    movb $48, (%rsi)
    jmp .Lpui_write
.Lpui_digit_loop:
    decq %rsi
    xorq %rdx, %rdx
    movq $10, %rcx
    divq %rcx
    addb $48, %dl
    movb %dl, (%rsi)
    testq %rax, %rax
    jnz .Lpui_digit_loop
.Lpui_write:
    leaq print_buf+32(%rip), %rdx
    subq %rsi, %rdx
    movq $1, %rdi
    leaq return_stack+1048568(%rip), %rcx
    cmpq %rcx, %r14
    ja return_stack_overflow
    addq $8, %r14
    leaq .Lprint_uint_write_done_3(%rip), %rax
    movq %rax, -8(%r14)
    jmp write_all
.Lprint_uint_write_done_3:
    subq $8, %r14
    jmpq *(%r14)

print_str:
    movq (%rdi), %rdx
    leaq 8(%rdi), %rsi
    movq $1, %rdi
    leaq return_stack+1048568(%rip), %rcx
    cmpq %rcx, %r14
    ja return_stack_overflow
    addq $8, %r14
    leaq .Lprint_str_write_done_4(%rip), %rax
    movq %rax, -8(%r14)
    jmp write_all
.Lprint_str_write_done_4:
    subq $8, %r14
    jmpq *(%r14)

encode_char:
    leaq print_buf(%rip), %rsi
    cmpq $127, %rdi
    ja .Lec_two
    movb %dil, (%rsi)
    movq $1, %rdx
    jmp .Lec_return
.Lec_two:
    cmpq $2047, %rdi
    ja .Lec_three
    movq %rdi, %rax
    shrq $6, %rax
    orb $192, %al
    movb %al, (%rsi)
    movq %rdi, %rax
    andb $63, %al
    orb $128, %al
    movb %al, 1(%rsi)
    movq $2, %rdx
    jmp .Lec_return
.Lec_three:
    cmpq $65535, %rdi
    ja .Lec_four
    movq %rdi, %rax
    shrq $12, %rax
    orb $224, %al
    movb %al, (%rsi)
    movq %rdi, %rax
    shrq $6, %rax
    andb $63, %al
    orb $128, %al
    movb %al, 1(%rsi)
    movq %rdi, %rax
    andb $63, %al
    orb $128, %al
    movb %al, 2(%rsi)
    movq $3, %rdx
    jmp .Lec_return
.Lec_four:
    movq %rdi, %rax
    shrq $18, %rax
    orb $240, %al
    movb %al, (%rsi)
    movq %rdi, %rax
    shrq $12, %rax
    andb $63, %al
    orb $128, %al
    movb %al, 1(%rsi)
    movq %rdi, %rax
    shrq $6, %rax
    andb $63, %al
    orb $128, %al
    movb %al, 2(%rsi)
    movq %rdi, %rax
    andb $63, %al
    orb $128, %al
    movb %al, 3(%rsi)
    movq $4, %rdx
.Lec_return:
    subq $8, %r14
    jmpq *(%r14)

primitive_to_str:
    cmpq $2, %r8
    je .Lpts_bool
    cmpq $3, %r8
    je .Lpts_char
    cmpq $4, %r8
    je .Lpts_cstr
    movq %rdi, %rax
    leaq print_buf+32(%rip), %rsi
    testq %rax, %rax
    jnz .Lpts_integer_nonzero
    decq %rsi
    movb $48, (%rsi)
    jmp .Lpts_integer_done
.Lpts_integer_nonzero:
    testq %r8, %r8
    jnz .Lpts_integer_abs
    testq %rax, %rax
    jns .Lpts_integer_abs
    negq %rax
.Lpts_integer_abs:
    movq $10, %rcx
.Lpts_integer_loop:
    decq %rsi
    xorq %rdx, %rdx
    divq %rcx
    addb $48, %dl
    movb %dl, (%rsi)
    testq %rax, %rax
    jnz .Lpts_integer_loop
    testq %r8, %r8
    jnz .Lpts_integer_done
    testq %rdi, %rdi
    jns .Lpts_integer_done
    decq %rsi
    movb $45, (%rsi)
.Lpts_integer_done:
    leaq print_buf+32(%rip), %rdx
    subq %rsi, %rdx
    jmp .Lpts_copy
.Lpts_bool:
    testq %rdi, %rdi
    jz .Lpts_bool_false
    leaq bool_true(%rip), %rsi
    movq $4, %rdx
    jmp .Lpts_copy
.Lpts_bool_false:
    leaq bool_false(%rip), %rsi
    movq $5, %rdx
    jmp .Lpts_copy
.Lpts_char:
    leaq return_stack+1048568(%rip), %rcx
    cmpq %rcx, %r14
    ja return_stack_overflow
    addq $8, %r14
    leaq .Lpts_char_encoded_5(%rip), %rax
    movq %rax, -8(%r14)
    jmp encode_char
.Lpts_char_encoded_5:
    jmp .Lpts_copy
.Lpts_cstr:
    movq %rdi, %rsi
    movq %rdi, %rax
.Lpts_cstr_loop:
    cmpb $0, (%rax)
    je .Lpts_cstr_done
    incq %rax
    jmp .Lpts_cstr_loop
.Lpts_cstr_done:
    movq %rax, %rdx
    subq %rsi, %rdx
.Lpts_copy:
    pushq %rsi
    pushq %rdx
    movq %rdx, %rdi
    addq $9, %rdi
    jc .Lheap_alloc_oom
    leaq return_stack+1048568(%rip), %rcx
    cmpq %rcx, %r14
    ja return_stack_overflow
    addq $8, %r14
    leaq .Lprimitive_string_data_done_6(%rip), %rax
    movq %rax, -8(%r14)
    jmp heap_alloc
.Lprimitive_string_data_done_6:
    popq %r13
    popq %rdx
    popq %rsi
    movq %rdx, (%r13)
    leaq 8(%r13), %rdi
    movq %rdx, %rcx
    rep movsb
    movb $0, (%rdi)
    movq $8, %rdi
    leaq return_stack+1048568(%rip), %rcx
    cmpq %rcx, %r14
    ja return_stack_overflow
    addq $8, %r14
    leaq .Lprimitive_string_wrapper_done_7(%rip), %rax
    movq %rax, -8(%r14)
    jmp heap_alloc
.Lprimitive_string_wrapper_done_7:
    popq %rax
    movq %r13, (%rax)
    pushq %rax
    subq $8, %r14
    jmpq *(%r14)

str_concat:
    movq %rdi, %r15
    movq %rsp, %r12
    xorq %r10, %r10
    xorq %rcx, %rcx
.Lsc_len_loop:
    cmpq %r15, %rcx
    jge .Lsc_len_done
    movq (%r12, %rcx, 8), %rax
    movq (%rax), %rax
    addq (%rax), %r10
    jc .Lheap_alloc_oom
    incq %rcx
    jmp .Lsc_len_loop
.Lsc_len_done:
    movq %r10, %rdi
    addq $9, %rdi
    jc .Lheap_alloc_oom
    leaq return_stack+1048568(%rip), %rcx
    cmpq %rcx, %r14
    ja return_stack_overflow
    addq $8, %r14
    leaq .Lconcat_string_data_done_8(%rip), %rax
    movq %rax, -8(%r14)
    jmp heap_alloc
.Lconcat_string_data_done_8:
    popq %r13
    movq %r10, (%r13)
    leaq 8(%r13), %rdi
    movq %r15, %rcx
    decq %rcx
.Lsc_copy_loop:
    cmpq $0, %rcx
    jl .Lsc_copy_done
    movq (%r12, %rcx, 8), %rsi
    movq (%rsi), %rsi
    movq (%rsi), %rdx
    addq $8, %rsi
    pushq %rcx
    movq %rdx, %rcx
    rep movsb
    popq %rcx
    decq %rcx
    jmp .Lsc_copy_loop
.Lsc_copy_done:
    movb $0, (%rdi)
    xorq %rcx, %rcx
.Lsc_free_loop:
    cmpq %r15, %rcx
    jge .Lsc_free_done
    movq (%r12, %rcx, 8), %rbx
    pushq %rcx
    movq (%rbx), %rdi
    leaq return_stack+1048568(%rip), %rcx
    cmpq %rcx, %r14
    ja return_stack_overflow
    addq $8, %r14
    leaq .Lconcat_part_data_free_done_9(%rip), %rax
    movq %rax, -8(%r14)
    jmp heap_free
.Lconcat_part_data_free_done_9:
    movq %rbx, %rdi
    leaq return_stack+1048568(%rip), %rcx
    cmpq %rcx, %r14
    ja return_stack_overflow
    addq $8, %r14
    leaq .Lconcat_part_wrapper_free_done_10(%rip), %rax
    movq %rax, -8(%r14)
    jmp heap_free
.Lconcat_part_wrapper_free_done_10:
    popq %rcx
    incq %rcx
    jmp .Lsc_free_loop
.Lsc_free_done:
    movq $8, %rdi
    leaq return_stack+1048568(%rip), %rcx
    cmpq %rcx, %r14
    ja return_stack_overflow
    addq $8, %r14
    leaq .Lconcat_string_wrapper_done_11(%rip), %rax
    movq %rax, -8(%r14)
    jmp heap_alloc
.Lconcat_string_wrapper_done_11:
    popq %rax
    movq %r13, (%rax)
    leaq (%r12, %r15, 8), %rsp
    pushq %rax
    subq $8, %r14
    jmpq *(%r14)

arithmetic_error:
    leaq arithmetic_error_msg(%rip), %rsi
    movq $arithmetic_error_msg_len, %rdx
    movq $2, %rdi
    leaq return_stack+1048568(%rip), %rcx
    cmpq %rcx, %r14
    ja return_stack_overflow
    addq $8, %r14
    leaq .Larithmetic_error_write_done_12(%rip), %rax
    movq %rax, -8(%r14)
    jmp write_all
.Larithmetic_error_write_done_12:
    movq $1, %rdi
    movq $60, %rax
    syscall

return_stack_overflow:
    leaq return_stack_overflow_msg(%rip), %rsi
    movq $return_stack_overflow_msg_len, %rdx
    movq $2, %rdi
    movq $1, %rax
    syscall
    movq $1, %rdi
    movq $60, %rax
    syscall

env_stack_overflow:
    leaq env_stack_overflow_msg(%rip), %rsi
    movq $env_stack_overflow_msg_len, %rdx
    movq $2, %rdi
    leaq return_stack+1048568(%rip), %rcx
    cmpq %rcx, %r14
    ja return_stack_overflow
    addq $8, %r14
    leaq .Lenv_stack_overflow_write_done_13(%rip), %rax
    movq %rax, -8(%r14)
    jmp write_all
.Lenv_stack_overflow_write_done_13:
    movq $1, %rdi
    movq $60, %rax
    syscall

'''
