name: Self-hosted tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Download casac release binary
      run: |
        curl --silent --location --fail \
          --output casac \
          "https://github.com/frendsick/casa/releases/latest/download/casac"
        chmod +x casac
    - name: Run self-hosted tests
      run: ./tests/test_self_hosted.sh ./casac
