name: Test example programs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/checkout@v5
      with:
        ref: main
        path: main-src
    - name: Download casac release binary
      run: |
        curl --silent --location --fail \
          --output casac-release \
          "https://github.com/frendsick/casa/releases/latest/download/casac"
        chmod +x casac-release
    - name: Bootstrap stage0 compiler from main
      run: |
        cd main-src
        ../casac-release -L lib casa.casa -o ../casac-main
    - name: Bootstrap stage1 compiler from branch
      run: ./casac-main -L lib casa.casa -o casac-stage1
    - name: Test example programs
      run: ./tests/test_examples.sh ./casac-stage1
