name: Test example programs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CASAC_RELEASE_TAG: v1.9.1-temp.0
    steps:
    - uses: actions/checkout@v5
    - name: Download casac release binary
      run: |
        curl --silent --location --fail \
          --output casac-release \
          "https://github.com/frendsick/casa/releases/download/${CASAC_RELEASE_TAG}/casac"
        chmod +x casac-release
    - name: Bootstrap stage1 compiler from branch
      run: ./casac-release -L lib casa.casa -o casac-stage1
    - name: Test example programs
      run: ./tests/test_examples.sh ./casac-stage1
